apiVersion: v1
kind: Service
metadata:
  name: prism-service
spec:
  selector:
    app: prism
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism
spec:
  selector:
    matchLabels:
      app: prism
  replicas: 4
  template:
    metadata:
      labels:
        app: prism
    spec:
      containers:
      - name: prism
        image: prism:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000